import type { AutomationStepTypeDescriptor } from './automation.js';

export const AUTOMATION_BUILTIN_STEP_TYPES: AutomationStepTypeDescriptor[] = [
  {
    type: 'create-feature',
    title: 'Create Feature',
    description: 'Creates a new feature in the current project scope.',
    category: 'features',
    editorComponent: 'createFeature',
    inputContract: 'Optional defaults for feature fields.',
    outputContract: 'Created feature object.',
    configSchema: {
      type: 'object',
      fields: [
        { key: 'id', type: 'string', label: 'Feature ID' },
        { key: 'title', type: 'string', label: 'Title' },
        { key: 'description', type: 'string', label: 'Description' },
        { key: 'category', type: 'string', label: 'Category', defaultValue: 'Uncategorized' },
        { key: 'status', type: 'string', label: 'Status' },
        { key: 'branchName', type: 'string', label: 'Branch Name' },
        {
          key: 'make',
          type: 'boolean',
          label: 'Make (Start Immediately)',
          description: 'Create and start the feature immediately',
        },
      ],
    },
  },
  {
    type: 'manage-feature',
    title: 'Manage Feature',
    description: 'Starts, stops, edits, or deletes an existing feature.',
    category: 'features',
    editorComponent: 'manageFeature',
    inputContract: 'Optional feature patch object for edit action.',
    outputContract: 'Updated feature object or delete result.',
    configSchema: {
      type: 'object',
      fields: [
        {
          key: 'action',
          type: 'enum',
          required: true,
          label: 'Action',
          options: ['start', 'stop', 'edit', 'delete'],
        },
        { key: 'featureId', type: 'string', required: true, label: 'Feature ID' },
        { key: 'updates', type: 'json', label: 'Updates (edit action)' },
      ],
    },
  },
  {
    type: 'run-ai-prompt',
    title: 'Run AI Prompt',
    description: 'Executes a prompt with configurable model selection.',
    category: 'ai',
    editorComponent: 'runAiPrompt',
    inputContract: 'Optional prompt fallback when config.prompt is not set.',
    outputContract: 'Model text response and metadata.',
    configSchema: {
      type: 'object',
      fields: [
        { key: 'prompt', type: 'string', required: true, label: 'Prompt' },
        {
          key: 'model',
          type: 'json',
          label: 'Model',
          description: 'PhaseModelEntry object with model, thinkingLevel, and reasoningEffort',
        },
        { key: 'systemPrompt', type: 'string', label: 'System Prompt' },
        { key: 'maxTurns', type: 'number', label: 'Max Turns', defaultValue: 1 },
      ],
    },
  },
  {
    type: 'run-typescript-code',
    title: 'Run TypeScript Code',
    description: 'Executes TypeScript/JavaScript in a sandboxed context.',
    category: 'ai',
    editorComponent: 'runTypeScriptCode',
    inputContract: 'Available as `input` in the sandbox.',
    outputContract: 'Return value from executed code.',
    configSchema: {
      type: 'object',
      fields: [
        { key: 'code', type: 'string', required: true, label: 'Code' },
        { key: 'timeoutMs', type: 'number', label: 'Sandbox Timeout (ms)' },
      ],
    },
  },
  {
    type: 'define-variable',
    title: 'Define/Set Variable',
    description: 'Creates or updates workflow variables.',
    category: 'variables',
    editorComponent: 'defineVariable',
    inputContract: 'Used when config.value is not set.',
    outputContract: 'Assigned value.',
    configSchema: {
      type: 'object',
      fields: [
        { key: 'name', type: 'string', label: 'Variable Name' },
        { key: 'value', type: 'json', label: 'Value' },
        { key: 'defineOnly', type: 'boolean', label: 'Define Only' },
        { key: 'values', type: 'json', label: 'Bulk Values' },
      ],
    },
  },
  {
    type: 'call-http-endpoint',
    title: 'Call HTTP Endpoint',
    description: 'Makes HTTP requests with headers/body and interpolation.',
    category: 'integrations',
    editorComponent: 'callHttpEndpoint',
    inputContract: 'Optional request body fallback.',
    outputContract: 'HTTP status, headers, and response body.',
    configSchema: {
      type: 'object',
      fields: [
        {
          key: 'method',
          type: 'enum',
          label: 'Method',
          options: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'],
        },
        { key: 'url', type: 'string', required: true, label: 'URL' },
        { key: 'headers', type: 'json', label: 'Headers' },
        { key: 'body', type: 'json', label: 'Body' },
      ],
    },
  },
  {
    type: 'run-script-exec',
    title: 'Run Script/Exec',
    description: 'Executes shell commands or scripts.',
    category: 'integrations',
    editorComponent: 'runScriptExec',
    inputContract: 'Optional command fallback.',
    outputContract: 'stdout, stderr, and process metadata.',
    configSchema: {
      type: 'object',
      fields: [
        { key: 'command', type: 'string', required: true, label: 'Command' },
        { key: 'cwd', type: 'string', label: 'Working Directory' },
        { key: 'timeoutMs', type: 'number', label: 'Timeout (ms)' },
        { key: 'shell', type: 'boolean', label: 'Use Shell', defaultValue: true },
      ],
    },
  },
  {
    type: 'emit-event',
    title: 'Emit Event',
    description: 'Emits an internal Automaker event.',
    category: 'integrations',
    editorComponent: 'emitEvent',
    inputContract: 'Optional payload fallback.',
    outputContract: 'Event type and payload emitted.',
    configSchema: {
      type: 'object',
      fields: [
        { key: 'eventType', type: 'string', required: true, label: 'Event Type' },
        { key: 'payload', type: 'json', label: 'Payload' },
      ],
    },
  },
  {
    type: 'if',
    title: 'If (Conditional)',
    description: 'Branches execution based on a condition expression.',
    category: 'flow',
    editorComponent: 'ifConditional',
    inputContract: 'Used by nested steps as initial input.',
    outputContract: 'Output from the executed branch.',
    configSchema: {
      type: 'object',
      fields: [
        { key: 'condition', type: 'string', required: true, label: 'Condition Expression' },
        { key: 'thenSteps', type: 'json', label: 'Then Steps' },
        { key: 'elseSteps', type: 'json', label: 'Else Steps' },
      ],
    },
  },
  {
    type: 'loop',
    title: 'Loop',
    description: 'Repeats nested steps over a list or fixed count.',
    category: 'flow',
    editorComponent: 'loop',
    inputContract: 'Used as default item source.',
    outputContract: 'Iteration summary and nested outputs.',
    configSchema: {
      type: 'object',
      fields: [
        { key: 'count', type: 'number', label: 'Count' },
        { key: 'items', type: 'json', label: 'Items' },
        { key: 'steps', type: 'json', required: true, label: 'Nested Steps' },
        { key: 'itemVariable', type: 'string', label: 'Item Variable', defaultValue: 'loopItem' },
        {
          key: 'indexVariable',
          type: 'string',
          label: 'Index Variable',
          defaultValue: 'loopIndex',
        },
      ],
    },
  },
  {
    type: 'call-automation',
    title: 'Call Automation',
    description: 'Invokes another automation and returns its output.',
    category: 'flow',
    editorComponent: 'callAutomation',
    inputContract: 'Optional variables fallback.',
    outputContract: 'Child run info and output.',
    configSchema: {
      type: 'object',
      fields: [
        { key: 'automationId', type: 'string', required: true, label: 'Automation ID' },
        { key: 'scope', type: 'enum', label: 'Scope', options: ['global', 'project'] },
        { key: 'variables', type: 'json', label: 'Variables' },
      ],
    },
  },
  {
    type: 'git-status',
    title: 'Git Status',
    description:
      'Get the git status of a repository including staged, unstaged, and untracked files.',
    category: 'git',
    editorComponent: 'gitStatus',
    inputContract: 'Optional repository path override.',
    outputContract: 'Object with files array, current branch, and isClean flag.',
    configSchema: {
      type: 'object',
      fields: [
        { key: 'path', type: 'string', label: 'Repository Path' },
        { key: 'porcelain', type: 'boolean', label: 'Porcelain Output', defaultValue: true },
      ],
    },
  },
  {
    type: 'git-branch',
    title: 'Git Branch',
    description: 'Create, list, or delete git branches.',
    category: 'git',
    editorComponent: 'gitBranch',
    inputContract: 'Optional branch name fallback.',
    outputContract: 'Branch name(s) or operation result.',
    configSchema: {
      type: 'object',
      fields: [
        {
          key: 'action',
          type: 'enum',
          required: true,
          label: 'Action',
          options: ['list', 'create', 'delete', 'current'],
        },
        { key: 'branch', type: 'string', label: 'Branch Name' },
        { key: 'path', type: 'string', label: 'Repository Path' },
        { key: 'force', type: 'boolean', label: 'Force', defaultValue: false },
      ],
    },
  },
  {
    type: 'git-commit',
    title: 'Git Commit',
    description: 'Stage files and create a commit with a message.',
    category: 'git',
    editorComponent: 'gitCommit',
    inputContract: 'Optional commit message fallback.',
    outputContract: 'Object with commit hash, message, and files committed.',
    configSchema: {
      type: 'object',
      fields: [
        { key: 'message', type: 'string', required: true, label: 'Commit Message' },
        { key: 'path', type: 'string', label: 'Repository Path' },
        { key: 'files', type: 'string[]', label: 'Files to Stage' },
        { key: 'all', type: 'boolean', label: 'Stage All Changes', defaultValue: false },
        { key: 'allowEmpty', type: 'boolean', label: 'Allow Empty Commit', defaultValue: false },
      ],
    },
  },
  {
    type: 'git-push',
    title: 'Git Push',
    description: 'Push local commits to a remote repository.',
    category: 'git',
    editorComponent: 'gitPush',
    inputContract: 'None.',
    outputContract: 'Object with push result, remote, and branch.',
    configSchema: {
      type: 'object',
      fields: [
        { key: 'path', type: 'string', label: 'Repository Path' },
        { key: 'remote', type: 'string', label: 'Remote Name', defaultValue: 'origin' },
        { key: 'branch', type: 'string', label: 'Branch Name' },
        { key: 'force', type: 'boolean', label: 'Force Push', defaultValue: false },
        { key: 'setUpstream', type: 'boolean', label: 'Set Upstream', defaultValue: false },
      ],
    },
  },
  {
    type: 'git-pull',
    title: 'Git Pull',
    description: 'Pull changes from a remote repository.',
    category: 'git',
    editorComponent: 'gitPull',
    inputContract: 'None.',
    outputContract: 'Object with pull result, remote, and branch.',
    configSchema: {
      type: 'object',
      fields: [
        { key: 'path', type: 'string', label: 'Repository Path' },
        { key: 'remote', type: 'string', label: 'Remote Name', defaultValue: 'origin' },
        { key: 'branch', type: 'string', label: 'Branch Name' },
        { key: 'rebase', type: 'boolean', label: 'Use Rebase', defaultValue: false },
      ],
    },
  },
  {
    type: 'git-checkout',
    title: 'Git Checkout',
    description: 'Switch branches or restore working tree files.',
    category: 'git',
    editorComponent: 'gitCheckout',
    inputContract: 'Optional branch name fallback.',
    outputContract: 'Object with checkout result and current branch.',
    configSchema: {
      type: 'object',
      fields: [
        { key: 'branch', type: 'string', label: 'Branch Name' },
        { key: 'path', type: 'string', label: 'Repository Path' },
        { key: 'createBranch', type: 'boolean', label: 'Create Branch', defaultValue: false },
        { key: 'force', type: 'boolean', label: 'Force Checkout', defaultValue: false },
        { key: 'files', type: 'string[]', label: 'Files to Restore' },
      ],
    },
  },
  {
    type: 'start-auto-mode',
    title: 'Start Auto Mode',
    description: 'Start the autonomous feature execution loop for a project or worktree.',
    category: 'auto-mode',
    editorComponent: 'startAutoMode',
    inputContract: 'None.',
    outputContract: 'Object with success status, maxConcurrency, and message.',
    configSchema: {
      type: 'object',
      fields: [
        {
          key: 'branchName',
          type: 'string',
          label: 'Branch Name (Worktree)',
          description: 'Optional: target specific worktree by branch',
        },
        {
          key: 'maxConcurrency',
          type: 'number',
          label: 'Max Concurrency',
          description: 'Maximum concurrent features (default: from settings)',
        },
      ],
    },
  },
  {
    type: 'stop-auto-mode',
    title: 'Stop Auto Mode',
    description: 'Stop the autonomous feature execution loop for a project or worktree.',
    category: 'auto-mode',
    editorComponent: 'stopAutoMode',
    inputContract: 'None.',
    outputContract: 'Object with success status, runningFeaturesCount, and message.',
    configSchema: {
      type: 'object',
      fields: [
        {
          key: 'branchName',
          type: 'string',
          label: 'Branch Name (Worktree)',
          description: 'Optional: target specific worktree by branch',
        },
      ],
    },
  },
  {
    type: 'get-auto-mode-status',
    title: 'Get Auto Mode Status',
    description:
      'Get the current status of auto mode including running features and concurrency settings.',
    category: 'auto-mode',
    editorComponent: 'getAutoModeStatus',
    inputContract: 'None.',
    outputContract:
      'Object with isRunning, isAutoLoopRunning, runningFeatures, runningCount, maxConcurrency.',
    configSchema: {
      type: 'object',
      fields: [
        {
          key: 'branchName',
          type: 'string',
          label: 'Branch Name (Worktree)',
          description: 'Optional: target specific worktree by branch',
        },
      ],
    },
  },
  {
    type: 'set-auto-mode-concurrency',
    title: 'Set Auto Mode Concurrency',
    description: 'Set the maximum number of concurrent features for auto mode.',
    category: 'auto-mode',
    editorComponent: 'setAutoModeConcurrency',
    inputContract: 'None.',
    outputContract: 'Object with success status and updated maxConcurrency.',
    configSchema: {
      type: 'object',
      fields: [
        {
          key: 'maxConcurrency',
          type: 'number',
          required: true,
          label: 'Max Concurrency',
          description: 'Maximum concurrent features (must be >= 1)',
        },
        {
          key: 'branchName',
          type: 'string',
          label: 'Branch Name (Worktree)',
          description: 'Optional: target specific worktree by branch',
        },
      ],
    },
  },
];
